#!/bin/bash
kubectl apply -f mysql-secret.yaml
kubectl apply -f mysql-configmap.yaml
kubectl apply -f mysql-service.yaml
kubectl apply -f mysql-persistentvolume.yaml
kubectl apply -f mysql-persistentvolumeclaim.yaml
kubectl apply -f mysql-deployment.yaml
#Al ejecutarlos en este orden el deployment queda pendiente hasta que se ejecuten todos y ahi empieza a crear
kubectl apply -f wordpress-service.yaml 
kubectl apply -f wordpress-deployment.yaml 
#minikube addons enable ingress
kubectl apply -f wordpress-ingress.yaml
# para que funcione ingress con minikube tenemos que tener el addon instalado ($ minikube addons enable ingress)
# tambien para que podamos verlo debemos poner en /etc/hosts la ip que se corresponda con el host
#usar virtualbox en minikube

#para entrar al mysql $kubectl run -it --rm --image=mysql:5.6 --restart=Never mysql-client -- mysql -h mysql-service -ppassword


#para conseguir ip del servicio de wordpress: minikube service wordpress --url

