apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb-config
data:
  initdb.sql: |
      CREATE USER 'wordpress_cloud'@'%' IDENTIFIED BY 'password';
      GRANT CREATE,DELETE,INSERT,SELECT,UPDATE ON wordpress.* TO 'wordpress_cloud'@'%';
